version: '3'

services:
  fastapi_app:
    container_name: fastapi_app
    volumes:
      - ./app:/app
    build:
      context: ./docker/python/
    expose:
      - 80
    network_mode: host
    command:  uvicorn app:app --reload --host 0.0.0.0 --port 80

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi_app